site:
  title: RuboCop Docs
  url: https://docs.rubocop.org/
  start_page: 1.19@rubocop::index.adoc
  keys:
    google_analytics: 'UA-140153536-1'
content:
  sources:
  - url: https://github.com/rubocop/rubocop.git
    branches: ['master']
    tags: ['v1.0.0', 'v1.1.0', 'v1.2.0', 'v1.3.0', 'v1.4.0', 'v1.5.2', 'v1.6.0', 'v1.7.0', 'v1.8.0', 'v1.9.1', 'v1.10.0', 'v1.11.0', 'v1.12.0', 'v1.13.0', 'v1.14.0', 'v1.15.0', 'v1.16.0', 'v1.17.0', 'v1.18.4', 'v1.19.0']
    start_path: docs
  - url: https://github.com/rubocop/rubocop-ast.git
    branches: master
    tags: ['v1.0.1', 'v1.1.0', 'v1.2.0', 'v1.3.0', 'v1.4.0', 'v1.5.0', 'v1.6.0', 'v1.7.0']
    start_path: docs
  - url: https://github.com/rubocop/rubocop-minitest.git
    branches: master
    tags: ['v0.10.3', 'v0.11.1', 'v0.12.0', 'v0.13.0', 'v0.14.0', 'v0.15.0']
    start_path: docs
  - url: https://github.com/rubocop/rubocop-performance.git
    branches: master
    tags: ['v1.7.1', 'v1.8.1', 'v1.9.2', 'v1.10.2', 'v1.11.4']
    start_path: docs
  - url: https://github.com/rubocop/rubocop-rails.git
    branches: master
    tags: ['v2.7.1', 'v2.8.1', 'v2.9.1', 'v2.10.1', 'v2.11.2']
    start_path: docs
  - url: https://github.com/rubocop/rubocop-rspec.git
    branches: master
    tags: ['v1.44.0', 'v2.0.0', 'v2.1.0', 'v2.2.0', 'v2.3.0', 'v2.4.0']
    start_path: docs
  - url: https://github.com/utkarsh2102/rubocop-packaging.git
    branches: master
    tags: []
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    toc: ~
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./docs
